apiVersion: v1
kind: Secret
metadata:
  name: gh-token
  namespace: default
type: Opaque
stringData:
  # Replace <PAT> with a GitHub Personal Access Token that can create repositories in your org.
  token: <PAT>
